general.import = [ "./gruvbox.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "TX02 Nerd Font"

[scrolling]
history = 100000

[window]
dynamic_padding = true
opacity = 0.90
decorations = "Buttonless"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "None"
