general.import = [ "./gruvbox.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 6

[font.normal]
family = "TX02 Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = -1

[scrolling]
history = 100000

[window]
dynamic_padding = true
opacity = 0.9
