general.import = [ "./gruvbox.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 5.5

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Italic"

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000

[window]
dynamic_padding = true
opacity = 0.95
