general.import = [ "./gruvbox.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.offset]
x = 1
y = 1

[font.normal]
family = "TX02 Nerd Font"

[scrolling]
history = 100000

[window]
dynamic_padding = true
blur = true
opacity = 0.85
decorations = "Buttonless"
option_as_alt = "Both"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "None"
