"$schema" = 'https://starship.rs/config-schema.json'

format = "$directory$git_branch $git_state$git_status$cmd_duration$character"

palette = 'gruvbox'
add_newline = false
command_timeout = 2000

[palettes.gruvbox]
aqua   = '#689D6A'
yellow = '#D79921'
blue   = '#458588'
orange = '#D65D0E'
red    = '#722529'
purple = '#B16286'
green  = '#98971A'
fg0    = '#FBF1C7'
bg1    = '#3C3836'
bg3    = '#665C54'

[cmd_duration]
min_time = 1000
show_milliseconds = false

[directory]
style = "bold fg:aqua"
truncation_length = 1
truncation_symbol = '…/'

[git_branch]
style = "bold fg:green"
symbol = ' '
format = '[$symbol$branch]($style)'

[git_state]
style = "bold fg:aqua"

[git_status]
style = "fg:aqua "
conflicted = '='
up_to_date = ''
untracked = '?${count}'
stashed = '\$${count}'
modified = '!${count}'
staged = '+${count}'
renamed = '»'
deleted = '✘'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[character]
success_symbol = '[❯](bold purple)'
error_symbol = '[❯](bold red)'

[package]
disabled = true
