add_newline = false

# A minimal left prompt
format = """$directory\
$git_branch\
$git_status\
$character"""

[directory]
truncation_length = 2
truncation_symbol = '…/'

[character]
success_symbol = "[❯](blue)"
error_symbol = "[✘](red)"
