"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
[](fg:color_red bg:color_yellow)\
$git_branch\
[](fg:color_yellow bg:color_orange)\
$git_state\
$git_status\
[](fg:color_orange bg:color_yellow)\
$cmd_duration\
[](fg:color_yellow)\
$character"""

add_newline = false
command_timeout = 2000
palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0    = '#D4BE98'
color_bg1    = '#1d2021'
color_bg3    = '#504945'
color_blue   = '#7daea3'
color_aqua   = '#89B482'
color_green  = '#A9B665'
color_orange = '#E78A4E'
color_purple = '#D3869B'
color_red    = '#EA6962'
color_yellow = '#D8A657'

[cmd_duration]
style  = 'fg:color_bg1 bg:color_yellow'
format = '[ $duration ]($style)'
show_milliseconds = false
min_time = 1000

[directory]
style            = "fg:color_bg1 bg:color_red"
format           = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = '…/'

[git_branch]
symbol = ""
style  = "bg:color_yellow"
format = '[[ $symbol $branch ](fg:color_bg1 bg:color_yellow)]($style)'

[git_state]
style  = "fg:color_bg1 bg:color_orange"
format = '[ $state( $progress_current/$progress_total) ]($style)'

[git_status]
style  = "bg:color_orange"
format = '[[ ($all_status$ahead_behind )](fg:color_bg1 bg:color_orange)]($style)'

[character]
success_symbol = " "
error_symbol   = " "

[package]
disabled = true
