format = """
$directory\
[](fg:color_love bg:color_gold)\
$git_branch\
[](fg:color_gold bg:color_rose)\
$git_state\
$git_status\
[](fg:color_rose)\
$character"""

right_format = """
[](fg:color_gold)\
$cmd_duration
[](fg:color_pine bg:color_gold)\
$nodejs
"""

add_newline = false
command_timeout = 2000
palette = 'rose_pine'


[palettes.rose_pine]
color_base = "#191724"
color_surface = "#1F1D2E"
color_overlay = "#26233A"
color_muted = "#6E6A86"
color_subtle = "#908CAA"
color_text = "#E0DEF4"
color_love = "#EB6F92"
color_gold = "#F6C177"
color_rose = "#EBBCBA"
color_pine = "#31748F"
color_foam = "#9CCFD8"
color_iris = "#C4A7E7"
color_highlightlow = "#21202E"
color_highlightmed = "#403D52"
color_highlighthigh = "#524F67 "

[cmd_duration]
style = 'fg:color_overlay bg:color_gold'
format = '[ $duration ]($style)'

[directory]
style = "fg:color_surface bg:color_love"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = '…/'

[character]
success_symbol = ''
error_symbol = ''

[git_branch]
symbol = ""
style = "bg:color_gold"
format = '[[ $symbol $branch ](fg:color_overlay bg:color_gold)]($style)'

[git_state]
style = "fg:color_surface bg:color_rose"
format ='[ $state( $progress_current/$progress_total) ]($style)'

[git_status]
style = "bg:color_rose"
format = '[[ ($all_status$ahead_behind )](fg:color_surface bg:color_rose)]($style)'

[nodejs]
symbol = ""
style = "bg:color_pine"
format = '[[ via $symbol ($version) ](fg:color_surface bg:color_pine)]($style)'
