format = """
$directory\
[](fg:color_red bg:color_yellow)\
$git_branch\
[](fg:color_yellow bg:color_orange)\
$git_state\
$git_status\
[](fg:color_orange)\
$character"""

add_newline = false
command_timeout = 2000
palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#FBF1C7'
color_bg1 = '#3C3836'
color_bg3 = '#665C54'
color_blue = '#458588'
color_aqua = '#689D6A'
color_green = '#98971A'
color_orange = '#D65D0E'
color_purple = '#B16286'
color_red = '#722529'
color_yellow = '#D79921'


[palettes.rose_pine]
color_base = "#191724"
color_surface = "#1F1D2E"
color_overlay = "#26233A"
color_muted = "#6E6A86"
color_subtle = "#908CAA"
color_text = "#E0DEF4"
color_love = "#EB6F92"
color_gold = "#F6C177"
color_rose = "#EBBCBA"
color_pine = "#31748F"
color_foam = "#9CCFD8"
color_iris = "#C4A7E7"
color_highlightlow = "#21202E"
color_highlightmed = "#403D52"
color_highlighthigh = "#524F67 "


[cmd_duration]
style = 'fg:color_overlay bg:color_yellow'
format = '[ $duration ]($style)'

[directory]
style = "fg:color_fg0 bg:color_red"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = '…/'

[character]
success_symbol = ''
error_symbol = ''

[git_branch]
symbol = ""
style = "bg:color_yellow"
format = '[[ $symbol $branch ](fg:color_bg1 bg:color_yellow)]($style)'

[git_state]
style = "fg:color_bg1 bg:color_orange"
format ='[ $state( $progress_current/$progress_total) ]($style)'

[git_status]
style = "bg:color_orange"
format = '[[ ($all_status$ahead_behind )](fg:color_bg1 bg:color_orange)]($style)'
