format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$cmd_duration $jobs $time\
$line_break\
$character"""

[nodejs]
format = "[$symbol($version )]($style)"

[fill]
symbol = " "

[directory]
style = "bold green"
read_only = " 󰌾"
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](blue)"
error_symbol = "[✘](red)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold purple"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
conflicted = "= "
ahead = "⇡×${count}"
behind = "⇣×${count}"
diverged = "⇡×${ahead_count} ⇣×${behind_count}"
untracked = "?×${count}"
stashed = "$"
modified = "!×${count}"
staged = "+×${count}"
renamed = ">>×${count}"
deleted = "✗×${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "bold yellow"

[memory_usage]
symbol = "󰍛"

[rust]
symbol = " "

[time]
disabled = false
style = "white"
format = "[$time]($style)"
time_format = "%a %v, %I:%M %p"
