format = """$directory\
$git_state\
$git_status\
$git_branch\
$git_metrics\
$character"""

add_newline = false

[directory]
truncation_length = 2
truncation_symbol = '…/'

[character]
success_symbol = '[❯](yellow)'
error_symbol = '[✘](red)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_metrics]
disabled = false
