Net/ThemeName "Gruvbox-Green-Dark"
Net/IconThemeName "Gruvbox-Dark"
Net/EnableEventDarwin 0
Net/EnableEventFdoStartup 0

Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/Antialias 1
Xft/RGBA "rgb"
Xft/DPI 98304
Xft/lcdfilter "lcddefault"

Gtk/ColorScheme "dark"
